version: '3.8'

services:
  # 1. Database Service (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: job_system_db
    ports:
      - "${DB_PORT}:5432" # Maps localhost:5432 -> container:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists data even if container restarts
    networks:
      - job_net

  # 2. Queue Service (Redis)
  redis:
    image: redis:7-alpine
    restart: always
    container_name: job_system_queue
    ports:
      - "${REDIS_PORT}:6379" # Maps localhost:6379 -> container:6379
    volumes:
      - redis_data:/data
    networks:
      - job_net

# Define volumes for persistence
volumes:
  postgres_data:
  redis_data:

    # Define a shared network
networks:
  job_net:
    driver: bridge
